spring.application.name=eventmanager
spring.datasource.url=jdbc:postgresql://localhost:5432/campus_event
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
